server:
  port: 8080
  servlet:
    context-path: /hello


spring:
  thymeleaf:
    cache: false
  profiles:
    active: local # set deploy profile

logging:
  config: classpath:logback/logback-spring.xml
  file:
    path: ../app-log/demo
    name: demo

welcome:
  message: Stoneberg
